blockChainMarketplace/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('blockChainMarketplace.wapp.urls', namespace='wapp')),
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

blockChainMarketplace/wapp/urls.py
from django.urls import path

from . import views

app_name = 'blockChainMarketplace'

urlpatterns = [
    path('', views.index, name='index'),
    path('sell', views.sell, name='sell'),
    path('sellExec', views.sellExec, name='sellExec'),
    path('<int:item_id>/buy', views.buy, name='buy'),
    path('<int:item_id>/pay', views.pay, name='pay'),
]

mysite/market/urls.py
from django.urls import path

from . import views

urlpatterns = [
    
    path('',views.HomePageView.as_view(), name = 'home'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include , path

urlpatterns = [
    path ('', include ('market.urls')),
    path ('users/',include('users.urls')),
    path ('users/',include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

blockChainMarketplace/wapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    address = models.CharField(max_length = 160)
    balance = models.FloatField(default = 500)
    pass

class SaleItem(models.Model):
    item_id = models.AutoField(primary_key=True)
    seller_id = models.ForeignKey(User, on_delete=models.CASCADE)
    item_name = models.CharField(max_length = 25)
    item_desc = models.CharField(max_length = 200)
    price = models.IntegerField()
    available = models.BooleanField(default=True)

class Txn(models.Model):
    seller_id = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name="seller")
    buyer_id = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name="buyer")
    item_id = models.ForeignKey(SaleItem, on_delete=models.DO_NOTHING)

mysite/market/models.py
from django.db import models

# Create your models here.
class username(models.Model) :
	username_text = models.CharField(max_length = 200)

class email(models.Model):
	email_text = models.CharField(max_length = 200)

mysite/users/models.py
from django.db import models

# Create your models here.
from django .contrib.auth.models import AbstractUser, UserManager

class CustomUserManager(UserManager):
	pass

class CustomUser(AbstractUser):
	objects = CustomUserManager()

mysite/users/forms.py
from django  import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm) :
	class Meta(UserCreationForm) :
		model = CustomUser
		fields = ('username','email')


class CustomUserChangeForm(UserChangeForm) :
	class Meta :
		model = CustomUser
		fields = UserChangeForm.Meta.fields

blockChainMarketplace/wapp/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from .models import SaleItem, Txn, User
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.

@login_required
def index(request):
    item_list = SaleItem.objects.all()
    template = loader.get_template('webapp/index.html')
    
    context = {
            'item_list': item_list
        }
    return HttpResponse(template.render(context, request))



def sell(request):
    template = loader.get_template('webapp/sell.html')
    return HttpResponse(template.render(None, request))

def sellExec(request):
    sell = SaleItem(seller_id=request.user, item_name=request.POST['item_name'], item_desc=request.POST['item_desc'], price=request.POST['price'])
    sell.save()
    item_list = SaleItem.objects.all()
    template = loader.get_template('webapp/index.html')
    context = {
            'item_list': item_list
        }
    return HttpResponse(template.render(context, request))

def buy(request, item_id):
    template = loader.get_template('webapp/buy.html')
    item = SaleItem.objects.get(item_id=item_id)
    context = {
                'item': item
            }
    return HttpResponse(template.render(context, request))

def pay(request, item_id):
    template = loader.get_template('webapp/index.html')
    item = SaleItem.objects.get(item_id=item_id)
    context = {
                'item': item
            }
    buyer = User.objects.get(username=request.user)
    if buyer.balance > item.price:
        buyer.balance = buyer.balance - item.price
        buyer.save()
        seller = User.objects.get(username=item.seller_id)
        seller.balance = seller.balance + item.price
        seller.save()
        txn = Txn(buyer_id=request.user, seller_id=item.seller_id, item_id=item)
        txn.save()
        item.available = False
        item.save()
        messages.add_message(request, messages.INFO, item.item_name + ' bought')
    else:
        messages.add_message(request, messages.INFO, item.item_name + ' could not be bought. Check balance')
    item_list = SaleItem.objects.all()
    context = {
            'item_list': item_list
        }
    return HttpResponse(template.render(context, request))

mysite/market/views.py
from django.views.generic import TemplateView



class HomePageView (TemplateView):
	template_name = 'home.html'

mysite/users/views.py
from django.shortcuts import render

# Create your views here.

blockChainMarketplace/wapp/templates/webapp/buy.html
<html>
	<head>
		<title>Buy</title>
	</head>
	<body>
		<h3>You've decided to buy {{item.item_name}}</h3>
		<div style="text-align:center; margin:10px">

			<form action="{% url 'wapp:pay' item.item_id %}" method="post">
			{% csrf_token %}
				<button style="left:50%" type="submit">Make Payment</button>
			</form>
		</div>
	</body>
</html>

blockChainMarketplace/wapp/templates/webapp/index.html
<html>
	<head>
		<title>
			Home
		</title>
	</head>
	<body>
		<h1>Welcome to Block Chain Marketplace {{user.username}}</h1>
		 <table style="width:100%">
  			<tr>
    				<th>Seller</th>
				<th>Item Name</th>
    				<th>Item Description</th>
    				<th>Price</th>
  			</tr>
			{% for item in item_list %}
			{% if item.available %}
  			<tr>
				<td>{{item.seller_id}}</td>
    				<td>{{item.item_name}}</td>
    				<td>{{item.item_desc}}</td>
				<td>{{item.price}}</td>
				<form action="{% url 'wapp:buy' item.item_id%}" method="post">
                        	{% csrf_token %}
				<td><button type="submit">Buy</button></td>
				</form>
  			</tr>
			{% endif %}
			{% endfor %}
		</table>
		<div style="text-align:center; margin:10px">
			<form action="{% url 'wapp:sell' %}" method="post">
			{% csrf_token %}
				<button style="left:50%" type="submit">I want to sell something</button>
			</form>
		</div>
		<form action='/accounts/logout'>

                <button type ="submit"> Log out</button>
                </form>
	{% if messages %}
	<ul class="messages">
    	{% for message in messages %}
    		<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    	{% endfor %}
	</ul>
	{% endif %}	
	</body>
</html>

blockChainMarketplace/wapp/templates/webapp/sell.html
<html>
	<head>
		<title>sell</title>
	</head>
	<body>
		<h1>What do you want to sell {{user.username}}?</h1>
		<form action="{% url 'wapp:sellExec' %}" method="post">
		{% csrf_token %}
		Item Name: <input type="text" name="item_name"><br>
		Item Description: <input type="text" name="item_desc"><br>
		Price: <input type="text" name="price"><br>
		<input type="submit" value="Sell"><br>
		</form>
	</body>
</html>

mysite/market/templates/home.html
<h1> market</h1>
<h2> Login</h2>

<p> welcome 
<p> <a href="{% url 'logout' %}> Log out </a></p>

<p> <p> <a href="{% url 'login' %}> Log In </a></p>